---
kind: pipeline
type: kubernetes
name: default

clone:
  disable: true

steps:
- name: test
  pull: if-not-exists
  image: alpine
  commands:
  - echo hello
  - echo world
  - exit 0
---
kind: signature
hmac: a66ccc6152b6ac7b90eb26fbe81b55bade1ae69a7b4408dc7e279ae2d9bac374

...
